### Imports ###
from os.path import join

### Config file ###
configfile: join('config', 'config.yaml')

### Setup ###
global_resources = workflow.global_resources

if 'gpus' in global_resources and global_resources['gpus'] > 0:
    assert global_resources['gpus'] == len(config['gpu_ids']), (
        'The number of GPUs in resources must match the length of '
        'provided GPU IDs'
    )

    USE_GPU = True
else:
    USE_GPU = False

### Config variables ###
input_dir = config['input_dir']
output_dir = config['output_dir']
outlier_ids = config['outlier_ids']
if outlier_ids is None:
    outlier_ids = []

### Input and output variables ###
include: join('rules', 'variables.smk')

### Rules ###
rule all:
    input:
        F_EXPRESSION_FILE
        # INDEGREE_FILE
    default_target:
        True

include: join('rules', 'preprocessing.smk')

if USE_GPU:
    include: join('rules', 'networks_gpu.smk')
else:
    include: join('rules', 'networks_cpu.smk')