### Imports ###
from os.path import dirname, join

### Config file ###
configfile: join('config', 'config.yaml')

### Setup ###
global_resources = workflow.global_resources

USE_GPU = ('gpus' in global_resources) and (global_resources['gpus'] > 0)

### Config variables ###
input_dir = config['input_dir']
output_dir = config['output_dir']
script_dir = config['script_dir']
template_dir = config['template_dir']
outlier_ids = config['outlier_ids']
if outlier_ids is None:
    outlier_ids = []

### Input and output variables ###
include: join('rules', 'variables.smk')

### Rules ###
rule all:
    input:
        INDEGREE_FILE,
        OUTDEGREE_FILE,
    default_target:
        True

include: join('rules', 'preprocessing.smk')
include: join('rules', 'networks.smk')
include: join('rules', 'comparison.smk')